server:
  port: 8081

spring:
  application:
    name: crypto-bot

exchange:
  url: 'http://localhost:8080'

bot:
  id: SMA

management:
  server:
    port: 8083
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics, httptrace
  endpoint:
    health:
      show-details: always

  metrics:
    distribution:
      percentiles-histogram:
        market.order.processing.duration: true
      percentiles:
        all: 0.5, 0.9, 0.95, 0.99
    enable:
      all: true
